runtime: go113
service: default
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80

handlers:
- url: /.*
  script: auto

vpc_access_connector:
  name: "projects/market-273905/locations/us-central1/connectors/market-connect"

env_variables:
  PORT: 8080
  SESSION_SECRET: asdfghjkl1234567890
  ADMIN_ACCOUNT_ID: f0c28384-3aa4-3f87-9fba-66a0aa62c504
  MYSQL_SOURCE: BambooTuna:pass@tcp(10.128.0.2:3306)/market
  MYSQL_USER: BambooTuna
  MYSQL_PASS: pass
  MYSQL_HOST: 10.128.0.2
  MYSQL_PORT: 3306
  MYSQL_DATABASE: market
  REDIS_HOST: 10.128.0.2
  REDIS_PORT: 6379
