runtime: nodejs10
service: default
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80

handlers:
  - url: /((.*)\.(js|css))$
    static_files: dist/\1
    upload: dist/(.*)\.(js|css)$

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html

vpc_access_connector:
  name: "projects/market-114/locations/asia-northeast1/connectors/market-connect"
